[2024-08-21T16:33:17.107+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-21T16:33:17.128+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_v1.create_postgres_table manual__2024-08-21T16:27:11.823314+00:00 [queued]>
[2024-08-21T16:33:17.137+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_v1.create_postgres_table manual__2024-08-21T16:27:11.823314+00:00 [queued]>
[2024-08-21T16:33:17.138+0000] {taskinstance.py:2856} INFO - Starting attempt 4 of 6
[2024-08-21T16:33:17.153+0000] {taskinstance.py:2879} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-08-21 16:27:11.823314+00:00
[2024-08-21T16:33:17.162+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1029) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-21T16:33:17.164+0000] {standard_task_runner.py:72} INFO - Started process 1030 to run task
[2024-08-21T16:33:17.162+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_v1', 'create_postgres_table', 'manual__2024-08-21T16:27:11.823314+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmptrjasl8y']
[2024-08-21T16:33:17.165+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask create_postgres_table
[2024-08-21T16:33:17.214+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_v1.create_postgres_table manual__2024-08-21T16:27:11.823314+00:00 [running]> on host 4bf35a2d5588
[2024-08-21T16:33:17.318+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='matea' AIRFLOW_CTX_DAG_ID='dag_with_postgres_v1' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T16:27:11.823314+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-21T16:27:11.823314+00:00'
[2024-08-21T16:33:17.319+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-21T16:33:17.345+0000] {sql.py:282} INFO - Executing: 
            create table if not exists dag_runs(
            dt date,
            dag_id character varying,
            primary key (dt, dag_id)
            )
            
[2024-08-21T16:33:17.355+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-08-21T16:33:17.365+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-08-21T16:33:17.372+0000] {sql.py:509} INFO - Running statement: 
            create table if not exists dag_runs(
            dt date,
            dag_id character varying,
            primary key (dt, dag_id)
            )
            , parameters: None
[2024-08-21T16:33:17.384+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-21T16:33:17.385+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_v1, task_id=create_postgres_table, run_id=manual__2024-08-21T16:27:11.823314+00:00, execution_date=20240821T162711, start_date=20240821T163317, end_date=20240821T163317
[2024-08-21T16:33:17.430+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-21T16:33:17.448+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-21T16:33:17.450+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
